import { Injectable } from '@angular/core';

@Injectable()
export class UtilitaireService {

    formattedDate(date):string{
        let dateformatted = '';
        if(date != null && date != undefined)
        {
            let splitted = date.split("-", 3);
            dateformatted = splitted[2]+'/'+splitted[1]+'/'+splitted[0];
        }
        return dateformatted;
    }

    getMarques():any
    {
        let tabMarque = ["ALEKO"
              ,"ALFA ROMEO"
              ,"ALPINE RENAULT"
              ,"ALPINE RENAULT"
              ,"ARO"
              ,"ASIA"
              ,"ASTON MARTIN"
              ,"AUDI"
              ,"AUSTIN"
              ,"AUTOBIANCHI"
              ,"AUVERLAND"
              ,"BEDFORD"
              ,"BEE BEE AUTOMOT"
              ,"BENTLEY"
              ,"BERTONE"
              ,"BMW"
              ,"BUICK"
              ,"CADILLAC"
              ,"CHEVROLET"
              ,"CHRYSLER"
              ,"CITROEN"
              ,"COURB"
              ,"DACIA"
              ,"DAEWOO"
              ,"DAF"
              ,"DAIHATSU"
              ,"DAIMLER"
              ,"DATSUN"
              ,"DODGE"
              ,"DS"
              ,"EBRO"
              ,"FIAT"
              ,"FISKER"
              ,"FORD"
              ,"FSO-POLSKI"
              ,"GAC GONOW"
              ,"GME"
              ,"GRANDIN"
              ,"HONDA"
              ,"HYUNDAI"
              ,"INFINITI"
              ,"INNOCENTI"
              ,"ISUZU"
              ,"IVECO"
              ,"JAGUAR"
              ,"JEEP"
              ,"KIA"
              ,"LADA"
              ,"LANCIA"
              ,"LAND ROVER"
              ,"LDV"
              ,"LEXUS"
              ,"LOTUS"
              ,"MAHINDRA"
              ,"MAN"
              ,"MARUTI"
              ,"MASERATI"
              ,"MATRA"
              ,"MAZDA"
              ,"MCC"
              ,"MEGA"
              ,"MERCEDES"
              ,"MG"
              ,"MIA"
              ,"MINI"
              ,"MITSUBISHI"
              ,"MPM MOTORS"
              ,"NISSAN"
              ,"OPEL"
              ,"PANHARD"
              ,"PEUGEOT"
              ,"PIAGGIO"
              ,"PONTIAC"
              ,"PORSCHE"
              ,"PROTON"
              ,"RENAULT"
              ,"ROVER"
              ,"SAAB"
              ,"SANTANA"
              ,"SEAT"
              ,"SKODA"
              ,"SMART"
              ,"SSANGYONG"
              ,"SUBARU"
              ,"SUNBEAM"
              ,"SUZUK"
              ,"TALBOT"
              ,"TATA"
              ,"TESLA"
              ,"THINK"
              ,"TOYOTA"
              ,"TRIUMPH"
              ,"UMM"
              ,"VOLKSWAGEN"
              ,"VOLVO"
              ,"ZASTAVA"
              ,"ZAZ"
              ,"Mon véhicule n'est pas répertorié"];

        return tabMarque;
    }
}